/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_coding_wbcryptolib_nativelib_SM2CoopJNI_SignSessionState */

#ifndef _Included_net_coding_wbcryptolib_nativelib_SM2CoopJNI_SignSessionState
#define _Included_net_coding_wbcryptolib_nativelib_SM2CoopJNI_SignSessionState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_SignSessionState
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024SignSessionState_init
  (JNIEnv *, jclass);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_SignSessionState
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024SignSessionState_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_SignSessionState
 * Method:    deserialize
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024SignSessionState_deserialize
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_SignSessionState
 * Method:    serialize
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024SignSessionState_serialize
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
