/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_coding_wbcryptolib_nativelib_SM2CoopJNI */

#ifndef _Included_net_coding_wbcryptolib_nativelib_SM2CoopJNI
#define _Included_net_coding_wbcryptolib_nativelib_SM2CoopJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI
 * Method:    encrypt
 * Signature: (J[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_encrypt
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI
 * Method:    decryptClientBegin
 * Signature: (J[B)Lorg/apache/commons/lang3/tuple/Pair;
 */
JNIEXPORT jobject JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_decryptClientBegin
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI
 * Method:    decryptServerRespond
 * Signature: (J[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_decryptServerRespond
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI
 * Method:    decryptClientComplete
 * Signature: (JJ[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_decryptClientComplete
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jbyteArray);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI
 * Method:    signClientBegin
 * Signature: (J[BJ)Lorg/apache/commons/lang3/tuple/Pair;
 */
JNIEXPORT jobject JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_signClientBegin
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI
 * Method:    signClientBeginWithID
 * Signature: (J[B[BJ)Lorg/apache/commons/lang3/tuple/Pair;
 */
JNIEXPORT jobject JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_signClientBeginWithID
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jlong);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI
 * Method:    signServerRespond
 * Signature: (J[B[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_signServerRespond
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jlong);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI
 * Method:    signClientComplete
 * Signature: (JJ[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_signClientComplete
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI
 * Method:    verify
 * Signature: (J[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_verify
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI
 * Method:    verifyWithID
 * Signature: (J[B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_verifyWithID
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
