/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_coding_wbcryptolib_nativelib_SM2CoopJNI_DecryptSessionState */

#ifndef _Included_net_coding_wbcryptolib_nativelib_SM2CoopJNI_DecryptSessionState
#define _Included_net_coding_wbcryptolib_nativelib_SM2CoopJNI_DecryptSessionState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_DecryptSessionState
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024DecryptSessionState_init
  (JNIEnv *, jclass);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_DecryptSessionState
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024DecryptSessionState_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_DecryptSessionState
 * Method:    deserialize
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024DecryptSessionState_deserialize
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_DecryptSessionState
 * Method:    serialize
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024DecryptSessionState_serialize
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
