/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_coding_wbcryptolib_nativelib_RBGJNI_MbedtlsCtrDRBG */

#ifndef _Included_net_coding_wbcryptolib_nativelib_RBGJNI_MbedtlsCtrDRBG
#define _Included_net_coding_wbcryptolib_nativelib_RBGJNI_MbedtlsCtrDRBG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_coding_wbcryptolib_nativelib_RBGJNI_MbedtlsCtrDRBG
 * Method:    withPlatformEntropy
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_net_coding_wbcryptolib_nativelib_RBGJNI_00024MbedtlsCtrDRBG_withPlatformEntropy
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_coding_wbcryptolib_nativelib_RBGJNI_MbedtlsCtrDRBG
 * Method:    withNullEntropy
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_net_coding_wbcryptolib_nativelib_RBGJNI_00024MbedtlsCtrDRBG_withNullEntropy
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_coding_wbcryptolib_nativelib_RBGJNI_MbedtlsCtrDRBG
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_coding_wbcryptolib_nativelib_RBGJNI_00024MbedtlsCtrDRBG_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
