/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_coding_wbcryptolib_nativelib_SM2CoopJNI_Context */

#ifndef _Included_net_coding_wbcryptolib_nativelib_SM2CoopJNI_Context
#define _Included_net_coding_wbcryptolib_nativelib_SM2CoopJNI_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_Context
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024Context_init
  (JNIEnv *, jclass);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_Context
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024Context_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_Context
 * Method:    setPublicKey
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024Context_setPublicKey
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_Context
 * Method:    setPrivateKey
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024Context_setPrivateKey
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_Context
 * Method:    setW
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024Context_setW
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_Context
 * Method:    getPublicKey
 * Signature: (J)Lorg/apache/commons/lang3/tuple/Pair;
 */
JNIEXPORT jobject JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024Context_getPublicKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_Context
 * Method:    getPrivateKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024Context_getPrivateKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_coding_wbcryptolib_nativelib_SM2CoopJNI_Context
 * Method:    getW
 * Signature: (J)Lorg/apache/commons/lang3/tuple/Pair;
 */
JNIEXPORT jobject JNICALL Java_net_coding_wbcryptolib_nativelib_SM2CoopJNI_00024Context_getW
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
